name: NoIP
description: |
  cliente de actualizaci칩n de DNS din치mico comprueba continuamente los cambios de direcci칩n IP en el fondo y actualiza autom치ticamente el DNS en No-IP cada vez que cambia.
version: v0.1
category: DNS
license: GPL v3